# Code created on project initialisation
name: "dbt_milly_project"
version: "1.0.0"
config-version: 2

profile: "dbt_milly_project"

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

# Modifications by me
models:
    dbt_milly_project:
        staging:
            materialized: view
        marts:
            intermediate:
                materialized: view
            materialized: table

vars:
    client: "ravelintest"
    partition: "2020-01-01"
    period: 5
    limit: 5
